-- Seed the cloud question bank from the original questions.json (252 questions).
-- Run this AFTER schema.sql. Safe to re-run: existing rows are updated, not duplicated.

insert into public.questions (id, category, en, zh, enabled, sort) values
('gk001', 'getting_to_know', 'Do you like yourself?', '你喜欢自己吗？', true, 0),
('gk002', 'getting_to_know', 'Are you satisfied with your own appearance?', '你对自己的容貌满意吗？？', true, 1),
('gk003', 'getting_to_know', 'What are the must-have essentials when you go out?', '你出门时必备的物品有哪些？', true, 2),
('gk004', 'getting_to_know', 'What are your social boundaries?', '你的社交界限有哪些？', true, 3),
('gk005', 'getting_to_know', 'Are you someone who will actively seek help?', '你是会主动寻求帮助的人吗？', true, 4),
('gk006', 'getting_to_know', 'Do you think you are real and honest?', '你觉得自己是一个真实的人吗？？', true, 5),
('gk007', 'getting_to_know', 'Tell us three things you feel grateful for.', '说出你生命中值得感恩的三件事情。', true, 6),
('gk008', 'getting_to_know', 'What kind of people do you hold bias to?', '你对哪类人会有潜意识的偏见？', true, 7),
('gk009', 'getting_to_know', 'When will you feel embarrassed?', '什么场景会让你感到尴尬？', true, 8),
('gk010', 'getting_to_know', 'Is there any difference between how you view yourself and how others view you?', '别人眼中的你，和你眼中的自己有区别吗？', true, 9),
('gk011', 'getting_to_know', 'Tell us five merits of yours. (You surely do have them!)', '说出自己的五个优点。（你一定有的！）', true, 10),
('gk012', 'getting_to_know', 'Do you have any hidden burden deep inside?', '你心中有隐藏的重担吗？', true, 11),
('gk013', 'getting_to_know', 'When people praise you, what would you like to hear?', '你最喜欢别人夸奖你什么？', true, 12),
('gk014', 'getting_to_know', 'What irritates you?', '什么事情会让你感到很生气？', true, 13),
('gk015', 'getting_to_know', 'How would you rank love, career, hobbies, family?', '你会怎么排序爱情，事业，爱好，家人？', true, 14),
('gk016', 'getting_to_know', 'What moment makes you feel your life is bright?', '什么时候会让你感觉生活充满光亮？', true, 15),
('gk017', 'getting_to_know', 'Speak out your three shortcomings bravely.', '你能勇敢地说出自己三个缺点吗？', true, 16),
('gk018', 'getting_to_know', 'What role do you play in a group?', '你觉得你在人群中是什么角色？', true, 17),
('gk019', 'getting_to_know', 'Do you act differently with people than alone?', '在人群中的你和私底下的你一样吗？', true, 18),
('gk020', 'getting_to_know', 'What are the characteristics of the people you admire?', '你欣赏的人普遍有什么特点呢？', true, 19),
('gk021', 'getting_to_know', 'What is your MBTI personality type? Do you think it describes you well?', '你的MBTI是什么？你觉得它描述得准确吗？', true, 20),
('gk022', 'getting_to_know', 'What is your Enneagram type? Do you think it describes you well?', '你的九型人格类型是什么？你觉得它描述得准确吗？', true, 21),
('gk023', 'getting_to_know', 'Are you the proactive one in social situations?', '你在社交场合中是积极主动的人吗？', true, 22),
('gk024', 'getting_to_know', 'What kind of people do you prefer to be friends with?', '你更容易跟什么样的人交朋友？', true, 23),
('gk025', 'getting_to_know', 'Ask back: pick another card and ask another person to answer for you.', '反问卡：再抽一张卡，让另一个人来回答这个问题。', true, 24),
('gk026', 'getting_to_know', 'Pass: you can choose to skip this question and pass to the next person.', '跳过卡：你可以选择跳过这个问题，直接传给下一个人。', true, 25),
('gk027', 'getting_to_know', 'Master card: you can pick a person to ask any one question.', '指定卡：你可以指定一个人问一个你想问的问题。', true, 26),
('gk028', 'getting_to_know', 'Friend card: get another card and pick a person to answer with you.', '陪伴卡：再抽一张卡，选一个人和你一起回答。', true, 27),
('gk029', 'getting_to_know', 'Flood card: take another card and everyone has to answer that question.', '洪水卡：抽取另一张卡，每个人都要回答那张卡上的问题。', true, 28),
('gk030', 'getting_to_know', 'In your browser history, what is the most embarrassing thing you have searched for?', '在你的浏览器历史记录中，你搜索过最尴尬的事情是什么？', true, 29),
('gk031', 'getting_to_know', 'What is the most ridiculous thing you have ever done?', '你做过的最荒唐的事情是什么？', true, 30),
('gk032', 'getting_to_know', 'Without mentioning your name, major of studies, and family origin, how would you introduce yourself?', '不能提你的名字、专业和家庭背景，你会怎么介绍自己？', true, 31),
('gk033', 'getting_to_know', 'What is the the first thing you want to do as you retire?', '你退休后第一件事想做什么？', true, 32),
('gk034', 'getting_to_know', 'If you have to give up one of chopsticks, spoons or forks, which would you choose to give up?', '如果必须放弃筷子、勺子或叉子中的一个，你会选择放弃哪一个？', true, 33),
('gk035', 'getting_to_know', 'If you can only eat one cuisine for the rest of your life, which cuisine would you choose?', '如果你只能吃一种菜系，你会选择哪一种？', true, 34),
('gk036', 'getting_to_know', 'Any ''wise saying'' or ''life motto'' you think is annoying or even useless?', '有没有什么“人生鸡汤”或“座右铭”你觉得很烦人甚至毫无意义？', true, 35),
('gk037', 'getting_to_know', 'Give two truths and one lie about yourself and pick a person to guess.', '说出两个关于你自己的真话和一个谎话，然后让另一个人来猜。', true, 36),
('gk038', 'getting_to_know', 'What food represents you the most?', '什么食物最能代表你？', true, 37),
('gk039', 'getting_to_know', 'What is your favorite emoji?', '你最喜欢的表情符号是什么？', true, 38),
('gk040', 'getting_to_know', 'What animal represents you the most?', '什么动物最能代表你？', true, 39),
('gk041', 'getting_to_know', 'I am the only one in this room ___________?', '我是这个屋子里唯一 __________。', true, 40),
('gk042', 'getting_to_know', 'What is the most useless thing you have ever bought?', '你买过的最智商税的东西是什么？', true, 41),
('gk043', 'getting_to_know', 'Explain your WeChat/Instagram profile name, avatar, and signature.', '解释一下你的微信/Instagram 名称、头像和签名！', true, 42),
('gk044', 'getting_to_know', 'What is the most ridiculous thing you have ever done to procrastinate on a ddl?', '你为了拖延DDL做过的最荒谬的事情是什么？', true, 43),
('gk045', 'getting_to_know', 'What is your weirdest sleeping spot at school or at work?', '你在学校或公司最奇怪的睡觉点是哪里？', true, 44),
('gk046', 'getting_to_know', 'What is the most ridiculous thing you have ever done to get out of a social event?', '你为了逃避社交活动做过的最荒谬的事情是什么？', true, 45),
('ir001', 'ideals_reals', 'What is your most ideal, comfortable day like?', '你觉得最舒服的一天应该是怎么样的？', true, 0),
('ir002', 'ideals_reals', 'What is your biggest dream?', '你最大的梦想是什么？', true, 1),
('ir003', 'ideals_reals', 'What makes you studying/working here?', '你为什么会来到这里上学/工作？', true, 2),
('ir004', 'ideals_reals', 'Do you like your area of studies?', '你喜欢自己的专业吗？', true, 3),
('ir005', 'ideals_reals', 'If you can choose to live in another city, where would you want to go?', '如果不在现在的城市居住，你想去哪里？', true, 4),
('ir006', 'ideals_reals', 'What are your short-term goals?', '你近期的小目标是什么？', true, 5),
('ir007', 'ideals_reals', 'What do you plan to study recently?', '你最近有打算学些什么呢？', true, 6),
('ir008', 'ideals_reals', 'What is it like when you are 70 years old?', '你70岁的时会是怎么样的？', true, 7),
('ir009', 'ideals_reals', 'What would you do if you have unlimited money?', '如果你有花不完的钱，你会做什么？', true, 8),
('ir010', 'ideals_reals', 'Where and how would you like to be when you die?', '你希望自己离世的时候是什么场景？', true, 9),
('ir011', 'ideals_reals', 'What is your biggest fear about the future?', '你对未来最大的恐惧是什么？', true, 10),
('ir012', 'ideals_reals', 'What is your biggest hope about the future?', '你对未来最大的期望是什么？', true, 11),
('ir013', 'ideals_reals', 'What is your ideal job?', '你理想的工作是什么？', true, 12),
('ir014', 'ideals_reals', 'What is your ideal family like?', '你理想的家庭是什么样子的？', true, 13),
('ir015', 'ideals_reals', 'What is your ideal relationship like?', '你理想的感情是什么样子的？', true, 14),
('ir016', 'ideals_reals', 'What is your ideal home like?', '你对未来住的房子的想象是什么样子的？', true, 15),
('ir017', 'ideals_reals', 'What is your ideal self like?', '你理想中的自己是什么样子的？', true, 16),
('ir018', 'ideals_reals', 'What is your ideal church like?', '你理想中的教会是什么样子的？', true, 17),
('ir019', 'ideals_reals', 'What is your ideal community like?', '你理想中的团契是什么样子的？', true, 18),
('ir020', 'ideals_reals', 'What is your ideal world like?', '你理想中的世界是什么样子的？', true, 19),
('ir021', 'ideals_reals', 'Ask back: pick another card and ask another person to answer for you.', '反问卡：再抽一张卡，让另一个人来回答这个问题。', true, 20),
('ir022', 'ideals_reals', 'Pass: you can choose to skip this question and pass to the next person.', '跳过卡：你可以选择跳过这个问题，直接传给下一个人。', true, 21),
('ir023', 'ideals_reals', 'Master card: you can pick a person to ask any one question.', '指定卡：你可以指定一个人问一个你想问的问题。', true, 22),
('ir024', 'ideals_reals', 'Friend card: get another card and pick a person to answer with you.', '陪伴卡：再抽一张卡，选一个人和你一起回答。', true, 23),
('ir025', 'ideals_reals', 'Flood card: take another card and everyone has to answer that question.', '洪水卡：抽取另一张卡，每个人都要回答那张卡上的问题。', true, 24),
('ir026', 'ideals_reals', 'If you can make anything your occupation, what would it be?', '如果你能把任何事情作为你的事业，你会做什么？', true, 25),
('ir027', 'ideals_reals', 'If you can live in any era of history, which era would you choose to live in?', '如果你可以选择生活在历史上的任何一个时代，你会选择哪个时代？', true, 26),
('ir028', 'ideals_reals', 'If you can have a superpower, what superpower would you choose?', '如果你可以拥有一种超能力，你会选择什么超能力？', true, 27),
('ir029', 'ideals_reals', 'If you can have dinner with any one person in the world, who would you choose to have dinner with?', '如果你可以和世界上的任何一个人共进晚餐，你会选择谁？', true, 28),
('ir030', 'ideals_reals', 'If you can be famous for something, what would you like to be famous for?', '如果你可以因为某件事而出名，你希望因为什么事而出名？', true, 29),
('ir031', 'ideals_reals', 'What is your never accomplished health plan?', '你最常做但从没成功的健康计划是什么？', true, 30),
('ir032', 'ideals_reals', 'If you can run a company that is completely useless, what would it sell?', '如果你可以经营一家完全无用的公司，它会卖什么？', true, 31),
('ir033', 'ideals_reals', 'If you can have a lifetime supply of something, what would you want to have a lifetime supply of?', '如果你可以拥有某样东西的终身供应，你希望是什么？', true, 32),
('ir034', 'ideals_reals', 'If you can have any animal as a pet, what animal would you choose to have as a pet?', '如果你可以养任何动物作为宠物，你会选择什么动物？', true, 33),
('ir035', 'ideals_reals', 'If you can exchange life with anyone for one day, who would you choose and why?', '如果你可以和任何人交换一天的生活，你会选择谁？为什么？', true, 34),
('ir036', 'ideals_reals', 'If you have to get stuck in an island with someone in the fellowship, who would it be and why?', '如果你必须和团契中的某个人被困在一个岛上，你会选择谁？为什么？', true, 35),
('ir037', 'ideals_reals', 'If you can have a billboard with anything on it, what would you put on the billboard?', '如果你可以拥有一个广告牌，上面可以写任何东西，你会在广告牌上写什么？', true, 36),
('ir038', 'ideals_reals', 'If you can have a theme song that plays whenever you enter a room, what would your theme song be?', '如果你可以有一首主题曲，每当你进入一个房间时都会播放，你的主题曲会是什么？', true, 37),
('ir039', 'ideals_reals', 'If you can have an extra hour everyday, what would you do with that extra hour?', '如果你可以每天多出一个小时，你会用这多出来的时间做什么？', true, 38),
('hh001', 'heart_to_heart', 'Describe the person on your right with three words.', '用三个词形容你右边的人。', true, 0),
('hh002', 'heart_to_heart', 'Of those who have passed away, whom do you miss? What would you like to say to them?', '你最想念哪位过世的人？如果还能见到他/她，会想说什么？', true, 1),
('hh003', 'heart_to_heart', 'Between you and your (future) partner, whom can you accept to die first?', '你和你的（未来）伴侣，你能接受谁先去世？', true, 2),
('hh004', 'heart_to_heart', 'What is the impact of your family of origin on you?', '原生家庭对你的影响有哪些？', true, 3),
('hh005', 'heart_to_heart', 'Whom do you feel grateful to the most?', '你最想感激的对象是谁？', true, 4),
('hh006', 'heart_to_heart', 'Are you the proactive one in a relationship? Why?', '你在一段感情中是主动的一方吗？为什么？', true, 5),
('hh007', 'heart_to_heart', 'What is your biggest fear/insecurity in a relationship?', '你在一段感情中最大的恐惧是什么？', true, 6),
('hh008', 'heart_to_heart', 'What is your father like?', '你的父亲是怎样的人？', true, 7),
('hh009', 'heart_to_heart', 'What is the most important thing you have learned from past relationships?', '你从过去的感情中学到了什么最重要的事？', true, 8),
('hh010', 'heart_to_heart', 'How do you handle conflicts in a relationship?', '你如何处理感情中的冲突？', true, 9),
('hh011', 'heart_to_heart', 'What is your mother like?', '你的母亲是怎样的人？', true, 10),
('hh012', 'heart_to_heart', 'Do you have siblings? How does it make who you are?', '你有兄弟姐妹吗？这对你有什么影响？', true, 11),
('hh013', 'heart_to_heart', 'Whom do you love the most?', '你最爱的人是谁？', true, 12),
('hh014', 'heart_to_heart', 'What behaviors do you dislike among friends?', '朋友之间，什么行为会让你反感？', true, 13),
('hh015', 'heart_to_heart', 'Do you have anyone that you owe an apology to? What do you want to say to him/her?', '你有对不起的人吗？想对他/她说什么？', true, 14),
('hh016', 'heart_to_heart', 'What is the most important value you look for in a friend?', '你在朋友身上最看重的特质是什么？', true, 15),
('hh017', 'heart_to_heart', 'How would you order the following five love languages: Words of affirmation, Quality time, Receiving gifts, Physical touch, Acts of service?', '你会怎么排序以下五种爱的语言：赞美鼓励，高质量的陪伴，礼物，肢体接触，实际行动上的帮助？', true, 16),
('hh018', 'heart_to_heart', 'What is the best advice you have ever received about relationships?', '你收到过的关于感情的最好建议是什么？', true, 17),
('hh019', 'heart_to_heart', 'How do you show love to others?', '你通常如何向别人表达爱意？', true, 18),
('hh020', 'heart_to_heart', 'What is your biggest relationship deal-breaker?', '在感情中，什么是你无法接受的底线？', true, 19),
('hh021', 'heart_to_heart', 'Can you live with long-distance relationship?', '你能接受异地恋吗？', true, 20),
('hh022', 'heart_to_heart', 'What is your love language?', '你的爱的语言是什么？', true, 21),
('hh023', 'heart_to_heart', 'Do you think TV-style romantic love is possible in real life?', '你觉得电视剧里甜甜的爱情可能发生在你身上吗？', true, 22),
('hh024', 'heart_to_heart', 'If you''re currently in a relationship, what is your love story?', '如果你目前在一段关系中，你可以分享你的爱情故事吗？', true, 23),
('hh025', 'heart_to_heart', 'What is the most romantic thing you have ever done or received?', '你做过或收到过的最浪漫的事情是什么？', true, 24),
('hh026', 'heart_to_heart', 'Are you more likely to be a dominant partner in a relationship?', '你是霸道总裁类型的恋人吗？', true, 25),
('hh027', 'heart_to_heart', 'Do you want to date someone in the same field as you?', '你希望和相同专业或者行业的人交往吗？', true, 26),
('hh028', 'heart_to_heart', 'What is the most important lesson you have learned from your parents'' relationship?', '你从父母的关系中学到了什么最重要的教训？', true, 27),
('hh029', 'heart_to_heart', 'What is the most important lesson you have learned from your past romantic relationships?', '你从过去的恋爱关系中学到最重要的事情是什么？', true, 28),
('hh030', 'heart_to_heart', 'What is your biggest insecurity in a relationship and how do you deal with it?', '你在感情中最大的自卑是什么？你是如何处理它的？', true, 29),
('hh031', 'heart_to_heart', 'Are you afraid of people hating your true self?', '你会害怕别人讨厌真实的你吗？', true, 30),
('hh032', 'heart_to_heart', 'In a relationship, how would you order the importance of his/her personality, family background, appearance, and finances?', '在一段关系中，你会如何排序对方的性格、家庭背景、外貌和经济状况的重要程度？', true, 31),
('hh033', 'heart_to_heart', 'Ask back: pick another card and ask another person to answer for you.', '反问卡：再抽一张卡，让另一个人来回答这个问题。', true, 32),
('hh034', 'heart_to_heart', 'Pass: you can choose to skip this question and pass to the next person.', '跳过卡：你可以选择跳过这个问题，直接传给下一个人。', true, 33),
('hh035', 'heart_to_heart', 'Master card: you can pick a person to ask any one question.', '指定卡：你可以指定一个人问一个你想问的问题。', true, 34),
('hh036', 'heart_to_heart', 'Friend card: get another card and pick a person to answer with you.', '陪伴卡：再抽一张卡，选一个人和你一起回答。', true, 35),
('hh037', 'heart_to_heart', 'When did you last cry and why?', '你最近一次流泪是什么时候，因为什么事情？', true, 36),
('hh038', 'heart_to_heart', 'Flood card: take another card and everyone has to answer that question.', '洪水卡：抽取另一张卡，每个人都要回答那张卡上的问题。', true, 37),
('hh039', 'heart_to_heart', 'Do you feel pressued when blending in a new group of people? Why?', '你觉得融入一个新群体有压力吗？为什么？', true, 38),
('hh040', 'heart_to_heart', 'What was the worst joke you have ever told', '你将过最失败的笑话是什么？', true, 39),
('hh041', 'heart_to_heart', 'What is your favorite villain?', '你最喜欢的大反派是谁？', true, 40),
('hh042', 'heart_to_heart', 'What is your biggest insecurity in a relationship and how do you deal with it?', '你在感情中最大的自卑是什么？你是如何处理它的？', true, 41),
('hh043', 'heart_to_heart', 'When was the last time you lied to your parents, for what?', '你最后一次对父母撒谎是什么时候？为什么？', true, 42),
('hh044', 'heart_to_heart', 'What is the most rebellious thing you have ever done in your life?', '你做过的最叛逆的事情是什么？', true, 43),
('hh045', 'heart_to_heart', 'Name one thing other feel envious about you, but you actually dislike?', '有没有一件别人很羡慕，但你其实不喜欢的事情？', true, 44),
('hh046', 'heart_to_heart', 'We all like to spend time with people we get along with, but there are often some people in the fellowship that you don''t get along with. Do you feel like those people are a burden to you?', '我们都喜欢跟合得来的人呆在一起，但团契常常有些合不来的人。你觉得这些人是你的负担吗？', true, 45),
('hh047', 'heart_to_heart', 'What is the most difficult thing for you to forgive?', '什么事情是你最难以原谅的？', true, 46),
('hh048', 'heart_to_heart', 'What is the most difficult thing for you to ask forgiveness for?', '什么事情是你最难以请求原谅的？', true, 47),
('hh049', 'heart_to_heart', 'What is the most difficult thing for you to apologize for?', '什么事情是你最难以道歉的？', true, 48),
('hh050', 'heart_to_heart', 'What is the most difficult thing for you to forgive yourself for?', '什么事情是你最难以原谅自己的？', true, 49),
('hh051', 'heart_to_heart', 'What do you think is the boundary between ''getting along'' and ''pretending nothing is wrong''?', '你觉得’和睦‘和’假装没事‘之间的界限在哪里？', true, 50),
('hh052', 'heart_to_heart', 'What is the most difficult thing for you to forgive in a relationship?', '在一段关系中，什么事情是你最难以原谅的？', true, 51),
('hh053', 'heart_to_heart', 'Roast your fellowship on one thing!', '吐槽你所在的团契一个点！', true, 52),
('hh054', 'heart_to_heart', 'What do you wish others could understand about you?', '有什么是你希望别人能理解你的地方？', true, 53),
('hh055', 'heart_to_heart', 'When someone has a completely different opinion from you, how do you handle it?', '当有人和你观点完全不一样时，你会怎么做？', true, 54),
('hh056', 'heart_to_heart', 'Can a fellowship exist without shared interests (e.g., not eating together, not playing together)?', '如果团契里没有共同兴趣（不一起吃饭，不一起玩），团契还能存在吗？', true, 55),
('hh057', 'heart_to_heart', 'Would you actively care about the people who are neglected in the fellowship?', '你会主动关心团契里被忽视的人吗？', true, 56),
('hh058', 'heart_to_heart', 'When you pray ''Lord, please grant us unity'', who do you actually hope to be changed first in your heart?', '当你祷告’主啊求你赐下合一‘时，你内心其实最希望谁先被改变？', true, 57),
('hh059', 'heart_to_heart', 'If God is asking a question to you, what are you afraid of Him asking?', '如果上帝今天亲口问你一个问题，你最怕祂问你什么？', true, 58),
('hh060', 'heart_to_heart', 'What are you most afraid of God asking you to forfeit?', '你最害怕上帝要你放下什么？', true, 59),
('hh061', 'heart_to_heart', 'Is forgiveness always possible, why or why not?', '宽恕总是可能的吗？为什么或为什么不？', true, 60),
('hh062', 'heart_to_heart', 'If you bring a new friend to the fellowship, what scenario are you most afraid of them seeing on the first day?', '如果你带一个新朋友来团契，你最怕ta第一天看到什么情景？', true, 61),
('hh063', 'heart_to_heart', 'What is the most painful part of growing up?', '你觉得’成长‘中最痛的部分是什么？', true, 62),
('mem001', 'memories', 'What is the most memorable memory that has shaped who you are?', '哪个记忆最深刻地塑造了现在的你？', true, 0),
('mem002', 'memories', 'Can you rate your childhood out of 10?', '你会给你的童年打几分（满分10分）？', true, 1),
('mem003', 'memories', 'What childhood moment made you grateful to God?', '哪个童年时刻让你对神充满感恩？', true, 2),
('mem004', 'memories', 'What is your favorite tv show as a child?', '你小时候最喜欢的电视节目是什么？', true, 3),
('mem005', 'memories', 'Describe your favorite trip.', '你最喜欢的旅行是哪一次呢？', true, 4),
('mem006', 'memories', 'Describe something that has made you feel ashamed.', '描述一件让你感到羞愧的事情吧。', true, 5),
('mem007', 'memories', 'What is your happiest memory?', '你最开心的记忆是什么？', true, 6),
('mem008', 'memories', 'What is your most adventurous experience?', '你最冒险的经历是什么？', true, 7),
('mem009', 'memories', 'Describe something that made you feel most regretful.', '描述一件你最后悔的事情吧。', true, 8),
('mem010', 'memories', 'When was the last time you cried and why?', '你最近一次哭是什么时候，因为什么事情？', true, 9),
('mem011', 'memories', 'What is the best thing you have ever done?', '你做过最棒的一件事是什么？', true, 10),
('mem012', 'memories', 'Describe your most memorable experience.', '你最忘不掉的经历是什么？', true, 11),
('mem013', 'memories', 'If you can reset for just one thing, what do you hope to change?', '如果有一件事可以重来，你最想要改变什么？？', true, 12),
('mem014', 'memories', 'What had made your week?', '这个星期有什么令你开心的事情？', true, 13),
('mem015', 'memories', 'What is the happiest moment for you so far?', '迄今为止，你最幸福的时刻是什么？', true, 14),
('mem016', 'memories', 'What is the most spontaneous thing you have ever done?', '你做过最冲动的事情是什么？', true, 15),
('mem017', 'memories', 'What is your favorite family tradition?', '你最喜欢的家庭传统是什么？', true, 16),
('mem018', 'memories', 'Describe a time when you overcame a significant challenge.', '描述一个你克服重大挑战的时刻吧。', true, 17),
('mem019', 'memories', 'What is the most rebellious experience you have ever had', '你做过最叛逆的事情是什么？', true, 18),
('mem020', 'memories', 'What is your most treasured memory?', '你最珍惜的记忆是什么？', true, 19),
('mem021', 'memories', 'What is the most embarrassing moment you have ever had?', '你经历过的最尴尬的时刻是什么？', true, 20),
('mem022', 'memories', 'What is the most meaningful thing you have ever done for someone else?', '你为别人做过的最有意义的事情是什么？', true, 21),
('mem023', 'memories', 'Describe a time when you felt truly proud of yourself.', '描述一个你感到真正为自己骄傲的时刻吧。', true, 22),
('mem024', 'memories', 'What is the most surprising thing that has ever happened to you?', '你经历过的最让人惊讶的事情是什么？', true, 23),
('mem025', 'memories', 'Name one experience you think is unique to you.', '说出一个你认为只有自己经历过的童年经历？', true, 24),
('mem026', 'memories', 'Ask back: pick another card and ask another person to answer for you.', '反问卡：再抽一张卡，让另一个人来回答这个问题。', true, 25),
('mem027', 'memories', 'Pass: you can choose to skip this question and pass to the next person.', '跳过卡：你可以选择跳过这个问题，直接传给下一个人。', true, 26),
('mem028', 'memories', 'Master card: you can pick a person to ask any one question.', '指定卡：你可以指定一个人问一个你想问的问题。', true, 27),
('mem029', 'memories', 'Friend card: get another card and pick a person to answer with you.', '陪伴卡：再抽一张卡，选一个人和你一起回答。', true, 28),
('mem030', 'memories', 'Flood card: take another card and everyone has to answer that question.', '洪水卡：抽取另一张卡，每个人都要回答那张卡上的问题。', true, 29),
('mem031', 'memories', 'What is the most memorable thing that has ever happened to you in this fellowship?', '在这个团契里，你经历过的最难忘的事情是什么？', true, 30),
('mem032', 'memories', 'What was your biggest fear as a child and what is your biggest fear now?', '小时候你最害怕什么？长大后你最害怕什么？', true, 31),
('mem033', 'memories', 'What is something you believed 100% as a child but later found out to be completely wrong?', '小时候你百分百相信，但现在却发现完全错误的事情是什么？', true, 32),
('mem034', 'memories', 'Have you changed your mind on something important before? What made you change your mind?', '你是否曾在某件重要的事情上改变过想法？是什么促成的？', true, 33),
('ms001', 'matters_of_soul', 'When you feel down, how do you want brothers and sisters to help you?', '当你感到沮丧时，你希望弟兄姐妹如何帮助你？', true, 0),
('ms002', 'matters_of_soul', 'If your partner chooses to commit his/her full life to God in service, how would you respond?', '如果你的伴侣选择将他/她的一生奉献给神，你会有何反应？', true, 1),
('ms003', 'matters_of_soul', 'What doubt has strengthened your faith?', '什么疑惑反而加深了你的信仰？', true, 2),
('ms004', 'matters_of_soul', 'What does true Christian friendship mean to you?', '真正的基督徒友谊对你意味着什么？', true, 3),
('ms005', 'matters_of_soul', 'How has God used community to heal you?', '神如何使用团契来医治你？', true, 4),
('ms006', 'matters_of_soul', 'How would you describe God in one word and why?', '如果要用一个词来形容神，你会用什么词汇？为什么？', true, 5),
('ms007', 'matters_of_soul', 'What Bible verse has changed your life?', '哪节经文对你影响最大？', true, 6),
('ms008', 'matters_of_soul', 'What miracle have you witnessed or experienced?', '你见证或经历过什么神迹？', true, 7),
('ms009', 'matters_of_soul', 'What kind of person do you think can go to heaven?', '你认为什么样的人可以去天堂？', true, 8),
('ms010', 'matters_of_soul', 'Are you willing to live forever?', '你愿意长生不老吗？', true, 9),
('ms011', 'matters_of_soul', 'What is freedom like to you?', '你心中的自由是什么样子的？', true, 10),
('ms012', 'matters_of_soul', 'What would you say to God if He stands in front of you?', '如果上帝站在你面前，你会对祂说什么？', true, 11),
('ms013', 'matters_of_soul', 'What would you ask God if you have one question to ask Him?', '如果你可以问上帝一个问题，你会问什么问题？', true, 12),
('ms014', 'matters_of_soul', 'Are you afraid of death?', '你惧怕死亡吗？', true, 13),
('ms015', 'matters_of_soul', 'Do you believe in divine power? Why?', '你相信有神吗？为什么？', true, 14),
('ms016', 'matters_of_soul', 'What provides you your spiritual support?', '什么是你的精神支柱？', true, 15),
('ms017', 'matters_of_soul', 'Life is short. If we are meant to vanish someday, why should we live this life?', '既然人生注定是短暂的，你为什么还要活这一生？', true, 16),
('ms018', 'matters_of_soul', 'How has your faith been challenged and how did you overcome it?', '你的信仰经历过哪些挑战，你是如何克服的？', true, 17),
('ms019', 'matters_of_soul', 'What is your favorite worship song and why?', '你最喜欢的敬拜歌曲是什么？为什么？', true, 18),
('ms020', 'matters_of_soul', 'What is your favorite Christian book and why?', '你最喜欢的基督教书籍是什么？为什么？', true, 19),
('ms021', 'matters_of_soul', 'What is your favorite Christian movie and why?', '你最喜欢的基督教电影是什么？为什么？', true, 20),
('ms022', 'matters_of_soul', 'Ask back: pick another card and ask another person to answer for you.', '反问卡：再抽一张卡，让另一个人来回答这个问题。', true, 21),
('ms023', 'matters_of_soul', 'Pass: you can choose to skip this question and pass to the next person.', '跳过卡：你可以选择跳过这个问题，直接传给下一个人。', true, 22),
('ms024', 'matters_of_soul', 'Master card: you can pick a person to ask any one question.', '指定卡：你可以指定一个人问一个你想问的问题。', true, 23),
('ms025', 'matters_of_soul', 'Friend card: get another card and pick a person to answer with you.', '陪伴卡：再抽一张卡，选一个人和你一起回答。', true, 24),
('ms026', 'matters_of_soul', 'If there is fellowship in heaven, what would you most like to do with your brothers and sisters?', '如果天堂里有团契，你觉得会有什么样的活动？', true, 25),
('ms027', 'matters_of_soul', 'How are you serving others lately in church/fellowship?', '你最近在教会/团契中是如何服侍他人的？', true, 26),
('ms028', 'matters_of_soul', 'What is your spiritual gift?', '你的属灵恩赐是什么?', true, 27),
('ms029', 'matters_of_soul', 'Flood card: take another card and everyone has to answer that question.', '洪水卡：抽取另一张卡，每个人都要回答那张卡上的问题。', true, 28),
('ms030', 'matters_of_soul', 'If there is a God who can answer all questions, what would you ask Him?', '如果有一位上帝能回答你的各种问题，你会问祂什么？', true, 29),
('ms031', 'matters_of_soul', 'Which spiritual persona are you afraid of the most? Why?', '你最害怕哪一种属灵人设？为什么？', true, 30),
('ms032', 'matters_of_soul', 'Rap card: pick another card and answer the question in a rap style.', '说唱卡：抽取另一张卡，并用说唱的方式回答那张卡上的问题。', true, 31),
('ms033', 'matters_of_soul', 'Double card: pick two cards and answer both questions.', '双倍卡：抽取两张卡，并回答两张卡上的两个问题。', true, 32),
('ms034', 'matters_of_soul', 'Silent card: you can choose to answer the question with a mime or a drawing instead of words.', '沉默卡：你可以选择用肢体表演或者画画的方式来回答这个问题，而不是用语言。', true, 33),
('ms035', 'matters_of_soul', 'If you can have a conversation with any one person in the Bible, who would you choose to have a conversation with and why?', '如果你可以和圣经中的任何一个人进行对话，你会选择和谁对话？为什么？', true, 34),
('ms036', 'matters_of_soul', 'If you can witness any one event in the Bible, which event would you choose to witness and why?', '如果你可以见证圣经中的任何一个事件，你会选择见证哪个事件？为什么？', true, 35),
('ms037', 'matters_of_soul', 'Do you think prayer change the world or change people? Why?', '你认为祷告是改变世界还是改变人？为什么？', true, 36),
('ms038', 'matters_of_soul', 'If you have to get stuck with a biblical character in the elevator for 24 hours, who would you NOT choose, why?', '如果你必须和圣经中的一位人物在电梯里困上24小时，你会选择不和谁一起？为什么？', true, 37),
('ms039', 'matters_of_soul', 'You want others to know that believing in Jesus is not actually _________, what would you fill in the blank with?', '你最想让别人知道信耶稣其实不是_________？', true, 38),
('ms040', 'matters_of_soul', 'Do you usually pray to change circumstances, change others, or change yourself?', '你通常祷告是为了改变环境、改变他人，还是改变自己？', true, 39),
('ms041', 'matters_of_soul', 'What is your least believing biblical promise?', '你现在最难相信的圣经应许是哪一个？', true, 40),
('ms042', 'matters_of_soul', 'What is your most believing biblical promise?', '你现在最相信的圣经应许是哪一个？', true, 41),
('ms043', 'matters_of_soul', 'If you can ask God to give you one spiritual gift, which spiritual gift would you ask for and why?', '如果你可以向神祈求赐予你一种属灵恩赐，你会祈求哪一种恩赐？为什么？', true, 42),
('ms044', 'matters_of_soul', 'If you can ask God to answer one prayer for you, which prayer would you ask Him to answer and why?', '如果你可以向神祈求回答一个祷告，你会祈求回答哪个祷告？为什么？', true, 43),
('ms045', 'matters_of_soul', 'What do you think is the most counter-intuitive truth about God?', '你认为关于上帝最反直觉的真理是什么？', true, 44),
('ms046', 'matters_of_soul', 'What kind of Christian do you want to be?', '你最想变成一个怎么样的基督徒？', true, 45),
('ms047', 'matters_of_soul', 'When was the last time you recognized a sin in your own life?', '你最近一次认识到自己的罪是什么时候？', true, 46),
('ms048', 'matters_of_soul', 'If ''being in Christ'' is not ''being the same'', what is it?', '如果‘在基督里合一’不是‘大家都一样’，它到底是什么？', true, 47),
('ms049', 'matters_of_soul', 'Have you met any fake Christians, when?', '你体会过‘虚假的基督徒’吗，具体什么事情？', true, 48),
('ms050', 'matters_of_soul', 'What is the difference between ''forgiveness'' and ''forgotteness'' in your life?', '在你的生命中，‘原谅’和‘遗忘’有什么区别？', true, 49),
('ms051', 'matters_of_soul', 'Have you ever been shocked by someone''s acceptance of you?', '你是否曾被某人对你的接纳所震惊？', true, 50),
('ms052', 'matters_of_soul', 'When you have wronged, do you tend to hide from God or seek Him?', '在当你做错事之后，你更容易躲着上帝还是找上帝？', true, 51),
('ms053', 'matters_of_soul', 'How has your faith changed your perspective on life?', '你的信仰如何改变了你对生活的看法？', true, 52),
('ms054', 'matters_of_soul', 'What is the most difficult thing about being a Christian?', '作为一个基督徒，最难的事情是什么？', true, 53),
('ms055', 'matters_of_soul', 'What has ''fellowship in Christ'' changed in your view of socialing?', '你觉得‘在基督里的团契’最打破你以往社交观念的地方是什么？', true, 54),
('ms056', 'matters_of_soul', '_______ has made me feel like I''m separated from the love of Christ.', '_______ 曾让我感觉就像与基督的爱隔绝了。', true, 55),
('ms057', 'matters_of_soul', 'Do you think ''growing'' is an additive process or a subtractive process?', '你觉得‘成长’是一种增加，还是一种被剥夺的过程？', true, 56),
('ms058', 'matters_of_soul', 'What is your biggest flip after believing in Jesus?', '你信主后最大的转变是什么？', true, 57),
('ms059', 'matters_of_soul', 'What difficulty are you facing, and how does it affect your faith in God?', '你最近遇到了哪些困境？它如何影响你对神的信心？', true, 58),
('ms060', 'matters_of_soul', 'Have Christians around you ever been a pressure to you?', '你身边的基督徒有成为过你的压力吗？在什么方面上？', true, 59),
('ms061', 'matters_of_soul', 'Double card: pick two cards and answer both questions.', '双倍卡：选择两张卡片并回答两个问题。', true, 60),
('ms062', 'matters_of_soul', 'Silent card: you can choose to answer the next question with a mime or a drawing instead of words.', '沉默卡：你可以选择用肢体表演或者画画的方式来回答这个问题，而不是用语言。', true, 61),
('ms063', 'matters_of_soul', 'Rap card: pick another card and answer the question in a rap style.', '说唱卡：抽取另一张卡，并用说唱的方式回答那张卡上的问题。', true, 62),
('ms064', 'matters_of_soul', 'Flood card: take another card and everyone has to answer that question.', '洪水卡：抽取另一张卡，每个人都要回答那张卡上的问题。', true, 63),
('ms065', 'matters_of_soul', 'If you can ask God to give you one spiritual gift, which spiritual gift would you ask for and why?', '如果你可以向神祈求赐予你一种属灵恩赐，你会祈求哪一种恩赐？为什么？', true, 64),
('ms066', 'matters_of_soul', 'Which Bible verse has made you feel like being ''slapped in the face''?', '有没有哪节经文让你觉得’被打脸‘？', true, 65),
('ms067', 'matters_of_soul', 'How do you differentiate between right and wrong?', '你如何判断什么是对是错？', true, 66),
('ms068', 'matters_of_soul', 'What is the most difficult sin for you to confess?', '什么罪是你最难以承认的？', true, 67),
('ms069', 'matters_of_soul', 'Do you have a question that you''ve been asking God for a long time without an answer?', '你有没有哪个问题问上帝很久都没有答案？', true, 68),
('ms070', 'matters_of_soul', 'Have you ever doubted that God really loves you?', '你曾经怀疑过上帝真的爱你吗？', true, 69)
on conflict (id) do update
  set category = excluded.category,
      en = excluded.en,
      zh = excluded.zh,
      sort = excluded.sort;
